name: ESLint

on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: Codestandards
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

      - name: "🔧 setup node"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 17

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

      - name: "🔍 lint code"
        run: npm run lint
